[project]
name = "yearn-risk-score"
version = "0.1.0"
description = "Yearn Risk Score tooling"
requires-python = ">=3.10"
dependencies = [
    "web3>=7.10.0",
    "python-dotenv>=1.1.0",
    "requests>=2.30.3",
    "ruff>=0.11.2",
]
